
function [mttpar] = Axon_numpar;
## [mttpar] = Axon_numpar;
## System Axon, representation numpar, language m; 
## File Axon_numpar.m; 
## Generated by MTT on Wed Dec  2 09:17:08 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(26,1);

## BEGIN Code

## User defined code from Axon_numpar.txt
  k_k =  1/1000;
  k_n =  1/1000;
  k_k =  1/1;
  k_n =  1/1;
  k_l =  1/1;
  v_i =  1;
  v_e =  1;
  rt =  8.3144621*300;		
  f =  96.4853399e3;			
  z	=  1;			
  c_m	=  1e-6;			
  v_eq	=  -65e-3;			
  kappa_k =   0.046262e-9;		
  kappa_n =   0.13204e-9;		
  kappa_l =   0.0014329e-9;	
  v_k	=  0;			
  v_n	=  0;			
  v_l     =  0;
  z	=  1;
  k_c =   5.7537;
  k_o =   1;
  k_cm =   105.49;
  k_om =   1;
  k_ch =   1;
  k_oh =     6.3281e-05;
  x_g  =  1e-9;
  v =  1;
  v_unit =  1e-9;
  kappa_k =  kappa_k/v_unit;
  kappa_n =  kappa_n/v_unit;
  kappa_l =  kappa_l/v_unit;
  c_m =  c_m/v_unit;
  g_s =  3e-6;

  ## Set up the mttpar vector
  mttpar(1)	= c_m;
  mttpar(2)	= f;
  mttpar(3)	= k_c;
  mttpar(4)	= k_ch;
  mttpar(5)	= k_cm;
  mttpar(6)	= k_o;
  mttpar(7)	= k_oh;
  mttpar(8)	= k_om;
  mttpar(9)	= k_k;
  mttpar(10)	= k_l;
  mttpar(11)	= k_n;
  mttpar(12)	= rt;
  mttpar(13)	= v;
  mttpar(14)	= v_e;
  mttpar(15)	= v_eq;
  mttpar(16)	= v_i;
  mttpar(17)	= g_s;
  mttpar(18)	= kappa_k;
  mttpar(19)	= kappa_l;
  mttpar(20)	= kappa_n;
  mttpar(21)	= v_k;
  mttpar(22)	= v_l;
  mttpar(23)	= v_n;
  mttpar(24)	= v_unit;
  mttpar(25)	= x_g;
  mttpar(26)	= z;
## END Code
endfunction
