
function [mtty] = Axon_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = Axon_odeo(mttx,mttu,mttt,mttpar);
## System Axon, representation odeo, language m; 
## File Axon_odeo.m; 
## Generated by MTT on Wed Dec  2 09:17:09 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   c_m 	= mttpar(1);
   f 	= mttpar(2);
   k_c 	= mttpar(3);
   k_ch 	= mttpar(4);
   k_cm 	= mttpar(5);
   k_o 	= mttpar(6);
   k_oh 	= mttpar(7);
   k_om 	= mttpar(8);
   k_k 	= mttpar(9);
   k_l 	= mttpar(10);
   k_n 	= mttpar(11);
   rt 	= mttpar(12);
   v 	= mttpar(13);
   v_e 	= mttpar(14);
   v_eq 	= mttpar(15);
   v_i 	= mttpar(16);
   g_s 	= mttpar(17);
   kappa_k 	= mttpar(18);
   kappa_l 	= mttpar(19);
   kappa_n 	= mttpar(20);
   v_k 	= mttpar(21);
   v_l 	= mttpar(22);
   v_n 	= mttpar(23);
   v_unit 	= mttpar(24);
   x_g 	= mttpar(25);
   z 	= mttpar(26);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;
mttx7 = mttx(7) ;
mttx8 = mttx(8) ;
mttx9 = mttx(9) ;
mttx10 = mttx(10) ;
mttx11 = mttx(11) ;
mttx12 = mttx(12) ;
mttx13 = mttx(13) ;
mttx14 = mttx(14) ;
mttx15 = mttx(15) ;
mttx16 = mttx(16) ;
mttx17 = mttx(17) ;
mttx18 = mttx(18) ;
mttx19 = mttx(19) ;
mttx20 = mttx(20) ;
mttx21 = mttx(21) ;
mttx22 = mttx(22) ;
mttx23 = mttx(23) ;
mttx24 = mttx(24) ;
mttx25 = mttx(25) ;
mttx26 = mttx(26) ;
mttx27 = mttx(27) ;
mttx28 = mttx(28) ;
mttx29 = mttx(29) ;
mttx30 = mttx(30) ;
mttx31 = mttx(31) ;
mttx32 = mttx(32) ;
mttx33 = mttx(33) ;
mttx34 = mttx(34) ;
mttx35 = mttx(35) ;
mttx36 = mttx(36) ;
mttx37 = mttx(37) ;
mttx38 = mttx(38) ;
mttx39 = mttx(39) ;
mttx40 = mttx(40) ;
mttx41 = mttx(41) ;
mttx42 = mttx(42) ;
mttx43 = mttx(43) ;
mttx44 = mttx(44) ;
mttx45 = mttx(45) ;
mttx46 = mttx(46) ;
mttx47 = mttx(47) ;
mttx48 = mttx(48) ;
mttx49 = mttx(49) ;
mttx50 = mttx(50) ;
mttx51 = mttx(51) ;
mttx52 = mttx(52) ;
mttx53 = mttx(53) ;
mttx54 = mttx(54) ;
mttx55 = mttx(55) ;
mttx56 = mttx(56) ;
mttx57 = mttx(57) ;
mttx58 = mttx(58) ;
mttx59 = mttx(59) ;
mttx60 = mttx(60) ;
mttx61 = mttx(61) ;
mttx62 = mttx(62) ;
mttx63 = mttx(63) ;
mttx64 = mttx(64) ;
mttx65 = mttx(65) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);
mttu4 = mttu(4);
mttu5 = mttu(5);
mttu6 = mttu(6);
mttu7 = mttu(7);
mttu8 = mttu(8);
mttu9 = mttu(9);
mttu10 = mttu(10);
mttu11 = mttu(11);
mttu12 = mttu(12);
mttu13 = mttu(13);
mttu14 = mttu(14);
mttu15 = mttu(15);
mttu16 = mttu(16);
mttu17 = mttu(17);
mttu18 = mttu(18);
mttu19 = mttu(19);
mttu20 = mttu(20);
mttu21 = mttu(21);
mttu22 = mttu(22);
mttu23 = mttu(23);
mttu24 = mttu(24);
mttu25 = mttu(25);
mttu26 = mttu(26);
mttu27 = mttu(27);
mttu28 = mttu(28);
mttu29 = mttu(29);
mttu30 = mttu(30);
mttu31 = mttu(31);
mttu32 = mttu(32);
mttu33 = mttu(33);
mttu34 = mttu(34);

## Unknown Inputs 

   mtty = zeros(34,1);

## BEGIN Code

## Code
  mtty(1) = mma_cr(1,(f**2*mttx1)/c_m)*(e**((f**2*mttx1)/(c_m*rt))*k_c*mttx2 -  \
k_o*mttx3);
  mtty(2) = (ghk_fun((f**2*mttx1)/c_m,v_k)*k_k*k_o**4*kappa_k*mttx3**4*(e**((f \
**2*mttx1*z)/(c_m*rt))*mttx4*v_e - mttx5*v_i))/(v_e*v_i*x_g**4);
  mtty(3) = mma_cr(2,(f**2*mttx1)/c_m)*(e**((3*f**2*mttx1)/(c_m*rt))*k_cm*mttx6 \
 - k_om*mttx7);
  mtty(4) = mma_cr(3,(f**2*mttx1)/c_m)*(e**((4*f**2*mttx1)/(c_m*rt))*k_ch*mttx8 \
 - k_oh*mttx9);
  mtty(5) = (ghk_fun((f**2*mttx1)/c_m,v_n)*k_ch*k_n*k_om**3*kappa_n*mttx7**3* \
  mttx8*(e**((f**2*mttx1*z)/(c_m*rt))*mttx10*v_e - mttx11*v_i))/(v_e*v_i*x_g**4);
  mtty(6) = (ghk_fun((f**2*mttx1)/c_m,v_l)*k_l*kappa_l*(e**((f**2*mttx1*z)/(c_m \
*rt))*mttx12*v_e - mttx13*v_i))/(v_e*v_i);
  mtty(7) = mma_cr(1,(f**2*mttx14)/c_m)*(e**((f**2*mttx14)/(c_m*rt))*k_c*mttx15 \
 - k_o*mttx16);
  mtty(8) = (ghk_fun((f**2*mttx14)/c_m,v_k)*k_k*k_o**4*kappa_k*mttx16**4*(e**(( \
f**2*mttx14*z)/(c_m*rt))*mttx17*v_e - mttx18*v_i))/(v_e*v_i*x_g**4);
  mtty(9) = mma_cr(2,(f**2*mttx14)/c_m)*(e**((3*f**2*mttx14)/(c_m*rt))*k_cm* \
  mttx19 - k_om*mttx20);
  mtty(10) = mma_cr(3,(f**2*mttx14)/c_m)*(e**((4*f**2*mttx14)/(c_m*rt))*k_ch* \
  mttx21 - k_oh*mttx22);
  mtty(11) = (ghk_fun((f**2*mttx14)/c_m,v_n)*k_ch*k_n*k_om**3*kappa_n*mttx20**3 \
*mttx21*(e**((f**2*mttx14*z)/(c_m*rt))*mttx23*v_e - mttx24*v_i))/(v_e*v_i*x_g**4 \
);
  mtty(12) = (ghk_fun((f**2*mttx14)/c_m,v_l)*k_l*kappa_l*(e**((f**2*mttx14*z)/( \
c_m*rt))*mttx25*v_e - mttx26*v_i))/(v_e*v_i);
  mtty(13) = mma_cr(1,(f**2*mttx27)/c_m)*(e**((f**2*mttx27)/(c_m*rt))*k_c* \
  mttx28 - k_o*mttx29);
  mtty(14) = (ghk_fun((f**2*mttx27)/c_m,v_k)*k_k*k_o**4*kappa_k*mttx29**4*(e**( \
(f**2*mttx27*z)/(c_m*rt))*mttx30*v_e - mttx31*v_i))/(v_e*v_i*x_g**4);
  mtty(15) = mma_cr(2,(f**2*mttx27)/c_m)*(e**((3*f**2*mttx27)/(c_m*rt))*k_cm* \
  mttx32 - k_om*mttx33);
  mtty(16) = mma_cr(3,(f**2*mttx27)/c_m)*(e**((4*f**2*mttx27)/(c_m*rt))*k_ch* \
  mttx34 - k_oh*mttx35);
  mtty(17) = (ghk_fun((f**2*mttx27)/c_m,v_n)*k_ch*k_n*k_om**3*kappa_n*mttx33**3 \
*mttx34*(e**((f**2*mttx27*z)/(c_m*rt))*mttx36*v_e - mttx37*v_i))/(v_e*v_i*x_g**4 \
);
  mtty(18) = (ghk_fun((f**2*mttx27)/c_m,v_l)*k_l*kappa_l*(e**((f**2*mttx27*z)/( \
c_m*rt))*mttx38*v_e - mttx39*v_i))/(v_e*v_i);
  mtty(19) = mma_cr(1,(f**2*mttx40)/c_m)*(e**((f**2*mttx40)/(c_m*rt))*k_c* \
  mttx41 - k_o*mttx42);
  mtty(20) = (ghk_fun((f**2*mttx40)/c_m,v_k)*k_k*k_o**4*kappa_k*mttx42**4*(e**( \
(f**2*mttx40*z)/(c_m*rt))*mttx43*v_e - mttx44*v_i))/(v_e*v_i*x_g**4);
  mtty(21) = mma_cr(2,(f**2*mttx40)/c_m)*(e**((3*f**2*mttx40)/(c_m*rt))*k_cm* \
  mttx45 - k_om*mttx46);
  mtty(22) = mma_cr(3,(f**2*mttx40)/c_m)*(e**((4*f**2*mttx40)/(c_m*rt))*k_ch* \
  mttx47 - k_oh*mttx48);
  mtty(23) = (ghk_fun((f**2*mttx40)/c_m,v_n)*k_ch*k_n*k_om**3*kappa_n*mttx46**3 \
*mttx47*(e**((f**2*mttx40*z)/(c_m*rt))*mttx49*v_e - mttx50*v_i))/(v_e*v_i*x_g**4 \
);
  mtty(24) = (ghk_fun((f**2*mttx40)/c_m,v_l)*k_l*kappa_l*(e**((f**2*mttx40*z)/( \
c_m*rt))*mttx51*v_e - mttx52*v_i))/(v_e*v_i);
  mtty(25) = mma_cr(1,(f**2*mttx53)/c_m)*(e**((f**2*mttx53)/(c_m*rt))*k_c* \
  mttx54 - k_o*mttx55);
  mtty(26) = (ghk_fun((f**2*mttx53)/c_m,v_k)*k_k*k_o**4*kappa_k*mttx55**4*(e**( \
(f**2*mttx53*z)/(c_m*rt))*mttx56*v_e - mttx57*v_i))/(v_e*v_i*x_g**4);
  mtty(27) = mma_cr(2,(f**2*mttx53)/c_m)*(e**((3*f**2*mttx53)/(c_m*rt))*k_cm* \
  mttx58 - k_om*mttx59);
  mtty(28) = mma_cr(3,(f**2*mttx53)/c_m)*(e**((4*f**2*mttx53)/(c_m*rt))*k_ch* \
  mttx60 - k_oh*mttx61);
  mtty(29) = (ghk_fun((f**2*mttx53)/c_m,v_n)*k_ch*k_n*k_om**3*kappa_n*mttx59**3 \
*mttx60*(e**((f**2*mttx53*z)/(c_m*rt))*mttx62*v_e - mttx63*v_i))/(v_e*v_i*x_g**4 \
);
  mtty(30) = (ghk_fun((f**2*mttx53)/c_m,v_l)*k_l*kappa_l*(e**((f**2*mttx53*z)/( \
c_m*rt))*mttx64*v_e - mttx65*v_i))/(v_e*v_i);
  mtty(31) = (f**2*g_s*(mttx1 - mttx14))/c_m;
  mtty(32) = (f**2*g_s*(mttx14 - mttx27))/c_m;
  mtty(33) = (f**2*g_s*(mttx27 - mttx40))/c_m;
  mtty(34) = (f**2*g_s*(mttx40 - mttx53))/c_m;
## END Code
endfunction
