
function [mtty] = Channel_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = Channel_odeo(mttx,mttu,mttt,mttpar);
## System Channel, representation odeo, language m; 
## File Channel_odeo.m; 
## Generated by MTT on Mon Mar  9 13:47:22 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k 	= mttpar(1);
   rt 	= mttpar(2);
   kappa 	= mttpar(3);
   z 	= mttpar(4);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);

## Unknown Inputs 

   mtty = zeros(1,1);

## BEGIN Code

## Code
  mtty(1) = e**(mttu2/rt)*k*kappa*(e**((mttu1*z)/rt)*mttx2 - mttx1);
## END Code
endfunction
