
function [mtty] = ChannelCequiv_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ChannelCequiv_odeo(mttx,mttu,mttt,mttpar);
## System ChannelCequiv, representation odeo, language m; 
## File ChannelCequiv_odeo.m; 
## Generated by MTT on Mon Mar  9 08:37:02 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k 	= mttpar(1);
   k_e 	= mttpar(2);
   rt 	= mttpar(3);
   g 	= mttpar(4);
   kappa 	= mttpar(5);
   z 	= mttpar(6);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

## Inputs 
mttu1 = mttu(1);

## Unknown Inputs 

   mtty = zeros(1,1);

## BEGIN Code

## Code
  mtty(1) = g*k*kappa*(e**(k_e*mttx3*z)*mttx1 - mttx2);
## END Code
endfunction
