
function [mtty] = ChannelKC_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ChannelKC_odeo(mttx,mttu,mttt,mttpar);
## System ChannelKC, representation odeo, language m; 
## File ChannelKC_odeo.m; 
## Generated by MTT on Fri Dec  4 08:42:19 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_c 	= mttpar(1);
   k_o 	= mttpar(2);
   k_k 	= mttpar(3);
   rt 	= mttpar(4);
   v_e 	= mttpar(5);
   v_i 	= mttpar(6);
   kappa_k 	= mttpar(7);
   v_k 	= mttpar(8);
   x_g 	= mttpar(9);
   z 	= mttpar(10);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);

## Unknown Inputs 

   mtty = zeros(2,1);

## BEGIN Code

## Code
  mtty(1) = mma_cr(1,mttx1)*(e**(mttx1/rt)*k_c*mttx2 - k_o*mttx3);
  mtty(2) = (ghk_fun(mttx1,v_k)*k_k*k_o**4*kappa_k*mttx3**4*(e**((mttx1*z)/rt)* \
  mttx4*v_e - mttx5*v_i))/(v_e*v_i*x_g**4);
## END Code
endfunction
