
function [mttpar] = ChannelKC_numpar;
## [mttpar] = ChannelKC_numpar;
## System ChannelKC, representation numpar, language m; 
## File ChannelKC_numpar.m; 
## Generated by MTT on Fri Dec  4 08:42:18 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(10,1);

## BEGIN Code

## User defined code from ChannelKC_numpar.txt
  v_i =  1;
  v_e =  1;
  k_k =  1/1000;
  rt =  8.3144621*300;		
  z	=  1;			
  kappa_k =   0.046262e-9;		
  v_k =  0;
  k_c =   5.7537;
  k_o =   1;
  x_g  =  0.001;

  ## Set up the mttpar vector
  mttpar(1)	= k_c;
  mttpar(2)	= k_o;
  mttpar(3)	= k_k;
  mttpar(4)	= rt;
  mttpar(5)	= v_e;
  mttpar(6)	= v_i;
  mttpar(7)	= kappa_k;
  mttpar(8)	= v_k;
  mttpar(9)	= x_g;
  mttpar(10)	= z;
## END Code
endfunction
