
function [mtty] = ChannelK_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ChannelK_odeo(mttx,mttu,mttt,mttpar);
## System ChannelK, representation odeo, language m; 
## File ChannelK_odeo.m; 
## Generated by MTT on Mon Mar  9 14:46:06 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_c 	= mttpar(1);
   k_o 	= mttpar(2);
   k_k 	= mttpar(3);
   rt 	= mttpar(4);
   v 	= mttpar(5);
   kappa_k 	= mttpar(6);
   v_k 	= mttpar(7);
   z 	= mttpar(8);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);

## Unknown Inputs 

   mtty = zeros(2,1);

## BEGIN Code

## Code
  mtty(1) = ghk_fun(v,v_k)*k_k*kappa_k*mttx4**4*(e**((v*z)/rt)*mttx1 - mttx2);
  mtty(2) = mma_cr(1,v)*(e**(v/rt)*k_c*mttx3 - k_o*mttx4);
## END Code
endfunction
