
function [mtty] = ChannelC_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ChannelC_odeo(mttx,mttu,mttt,mttpar);
## System ChannelC, representation odeo, language m; 
## File ChannelC_odeo.m; 
## Generated by MTT on Tue Mar 10 11:29:56 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   c 	= mttpar(1);
   f 	= mttpar(2);
   k 	= mttpar(3);
   rt 	= mttpar(4);
   g 	= mttpar(5);
   kappa 	= mttpar(6);
   z 	= mttpar(7);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

## Inputs 
mttu1 = mttu(1);

## Unknown Inputs 

   mtty = zeros(1,1);

## BEGIN Code

## Code
  mtty(1) = g*k*kappa*(e**((f*mttx3*z)/(c*rt))*mttx1 - mttx2);
## END Code
endfunction
