function [K i_lin] = ChannelNaC_K(mttpar)
## function [K i_lin] = ChannelNaC_K(mttpar)
## Generated by odeo2kpar on Thu Jul  9 10:27:25 AEST 2015

## Parameters 
   k_ch 	= mttpar(1);
   k_cm 	= mttpar(2);
   k_oh 	= mttpar(3);
   k_om 	= mttpar(4);
   k_n 	= mttpar(5);
   rt 	= mttpar(6);
   v_e 	= mttpar(7);
   v_i 	= mttpar(8);
   kappa_n 	= mttpar(9);
   v_n 	= mttpar(10);
   x_g 	= mttpar(11);
   z 	= mttpar(12);

## Free-energy constants
  K(2,1) =  k_cm;
  K(3,1) =  k_om;
  K(4,1) =  k_ch;
  K(5,1) =  k_oh;
  K(6,1) =  k_n/v_i;
  K(7,1) =  k_n/v_e;
if (min(K)==0); warning("K has a zero element"); endif
## Index of linear Cs
i_lin = [];
endfunction
