
function [mttpar] = Channel_numpar;
## [mttpar] = Channel_numpar;
## System Channel, representation numpar, language m; 
## File Channel_numpar.m; 
## Generated by MTT on Mon Mar  9 13:47:21 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(4,1);

## BEGIN Code

## User defined code from Channel_numpar.txt
  k	=  1.0; 
  rt	=  1.0; 
  kappa	=  1.0; 
  z	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k;
  mttpar(2)	= rt;
  mttpar(3)	= kappa;
  mttpar(4)	= z;
## END Code
endfunction
