
function [mtty] = GateNa_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = GateNa_odeo(mttx,mttu,mttt,mttpar);
## System GateNa, representation odeo, language m; 
## File GateNa_odeo.m; 
## Generated by MTT on Wed Mar 11 09:41:46 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_ch 	= mttpar(1);
   k_cm 	= mttpar(2);
   k_oh 	= mttpar(3);
   k_om 	= mttpar(4);
   rt 	= mttpar(5);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);

## Unknown Inputs 

   mtty = zeros(3,1);

## BEGIN Code

## Code
  mtty(1) = rt*(log(k_ch*mttx3) + 3*log(k_om*mttx2) - log(k_ch) - 3*log(k_om));
  mtty(2) = mma_cr(2,mttu1)*(e**((3*mttu1)/rt)*k_cm*mttx1 - k_om*mttx2);
  mtty(3) = mma_cr(3,mttu1)*(e**((4*mttu1)/rt)*k_ch*mttx3 - k_oh*mttx4);
## END Code
endfunction
