
function [mtty] = GateK_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = GateK_odeo(mttx,mttu,mttt,mttpar);
## System GateK, representation odeo, language m; 
## File GateK_odeo.m; 
## Generated by MTT on Wed Mar 11 08:54:04 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_c 	= mttpar(1);
   k_o 	= mttpar(2);
   rt 	= mttpar(3);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);

## Unknown Inputs 

   mtty = zeros(2,1);

## BEGIN Code

## Code
  mtty(1) = 4*rt*(log(k_o*mttx2) - log(k_o));
  mtty(2) = mma_cr(1,mttu1)*(e**(mttu1/rt)*k_c*mttx1 - k_o*mttx2);
## END Code
endfunction
