
function [mttpar] = GateK_numpar;
## [mttpar] = GateK_numpar;
## System GateK, representation numpar, language m; 
## File GateK_numpar.m; 
## Generated by MTT on Wed Mar 11 08:54:02 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(3,1);

## BEGIN Code

## User defined code from GateK_numpar.txt
  k_c	=  1.0; 
  k_o	=  1.0; 
  rt	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_c;
  mttpar(2)	= k_o;
  mttpar(3)	= rt;
## END Code
endfunction
