
function [mttpar] = HH_numpar;
## [mttpar] = HH_numpar;
## System HH, representation numpar, language m; 
## File HH_numpar.m; 
## Generated by MTT on Mon Mar 16 13:55:27 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(21,1);

## BEGIN Code

## User defined code from HH_numpar.txt
  i_app =  0;			
  k_k =  1/1000;
  k_n =  1/1000;
  k_k =  1/1;
  k_n =  1/1;
  rt =  8.3144621*300;		
  f =  96.4853399;			
  z	=  1;			
  c_m	=  1;
  v_eq	=  -65;			
  g_l	=  0.3;
  kappa_k =   0.48229;		
  kappa_n =   0.073575;		
  v_k =   -77;
  v_n =   50;
  v_l =   -54.4;
  kappa_k =   0.046262;		
  kappa_n =   0.13204;		
  v_k	=  0;			
  v_n	=  0;			
  v_l =   -54.4;
  v_l =  -64.5;
  z	=  1;
  k_c =   5.7537;
  k_o =   1;
  k_cm =   105.49;
  k_om =   1;
  k_ch =   1;
  k_oh =     6.3281e-05;
  n_g =  1;
  v =  1;

  ## Set up the mttpar vector
  mttpar(1)	= c_m;
  mttpar(2)	= f;
  mttpar(3)	= i_app;
  mttpar(4)	= k_c;
  mttpar(5)	= k_ch;
  mttpar(6)	= k_cm;
  mttpar(7)	= k_o;
  mttpar(8)	= k_oh;
  mttpar(9)	= k_om;
  mttpar(10)	= k_k;
  mttpar(11)	= k_n;
  mttpar(12)	= rt;
  mttpar(13)	= v;
  mttpar(14)	= v_eq;
  mttpar(15)	= g_l;
  mttpar(16)	= kappa_k;
  mttpar(17)	= kappa_n;
  mttpar(18)	= v_k;
  mttpar(19)	= v_l;
  mttpar(20)	= v_n;
  mttpar(21)	= z;
## END Code
endfunction
