
function [mtty] = Membrane_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = Membrane_odeo(mttx,mttu,mttt,mttpar);
## System Membrane, representation odeo, language m; 
## File Membrane_odeo.m; 
## Generated by MTT on Fri Dec  4 08:42:41 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   c_m 	= mttpar(1);
   f 	= mttpar(2);
   k_c 	= mttpar(3);
   k_ch 	= mttpar(4);
   k_cm 	= mttpar(5);
   k_o 	= mttpar(6);
   k_oh 	= mttpar(7);
   k_om 	= mttpar(8);
   k_k 	= mttpar(9);
   k_l 	= mttpar(10);
   k_n 	= mttpar(11);
   rt 	= mttpar(12);
   v 	= mttpar(13);
   v_e 	= mttpar(14);
   v_eq 	= mttpar(15);
   v_i 	= mttpar(16);
   kappa_k 	= mttpar(17);
   kappa_l 	= mttpar(18);
   kappa_n 	= mttpar(19);
   v_k 	= mttpar(20);
   v_l 	= mttpar(21);
   v_n 	= mttpar(22);
   v_unit 	= mttpar(23);
   x_g 	= mttpar(24);
   z 	= mttpar(25);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;
mttx7 = mttx(7) ;
mttx8 = mttx(8) ;
mttx9 = mttx(9) ;
mttx10 = mttx(10) ;
mttx11 = mttx(11) ;
mttx12 = mttx(12) ;
mttx13 = mttx(13) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);
mttu4 = mttu(4);
mttu5 = mttu(5);
mttu6 = mttu(6);

## Unknown Inputs 

   mtty = zeros(6,1);

## BEGIN Code

## Code
  mtty(1) = mma_cr(1,(f**2*mttx1)/c_m)*(e**((f**2*mttx1)/(c_m*rt))*k_c*mttx2 -  \
k_o*mttx3);
  mtty(2) = (ghk_fun((f**2*mttx1)/c_m,v_k)*k_k*k_o**4*kappa_k*mttx3**4*(e**((f \
**2*mttx1*z)/(c_m*rt))*mttx4*v_e - mttx5*v_i))/(v_e*v_i*x_g**4);
  mtty(3) = mma_cr(2,(f**2*mttx1)/c_m)*(e**((3*f**2*mttx1)/(c_m*rt))*k_cm*mttx6 \
 - k_om*mttx7);
  mtty(4) = mma_cr(3,(f**2*mttx1)/c_m)*(e**((4*f**2*mttx1)/(c_m*rt))*k_ch*mttx8 \
 - k_oh*mttx9);
  mtty(5) = (ghk_fun((f**2*mttx1)/c_m,v_n)*k_ch*k_n*k_om**3*kappa_n*mttx7**3* \
  mttx8*(e**((f**2*mttx1*z)/(c_m*rt))*mttx10*v_e - mttx11*v_i))/(v_e*v_i*x_g**4);
  mtty(6) = (ghk_fun((f**2*mttx1)/c_m,v_l)*k_l*kappa_l*(e**((f**2*mttx1*z)/(c_m \
*rt))*mttx12*v_e - mttx13*v_i))/(v_e*v_i);
## END Code
endfunction
