
function [mtty] = Pgate_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = Pgate_odeo(mttx,mttu,mttt,mttpar);
## System Pgate, representation odeo, language m; 
## File Pgate_odeo.m; 
## Generated by MTT on Wed Mar 11 08:50:24 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_c 	= mttpar(1);
   k_o 	= mttpar(2);
   rt 	= mttpar(3);
   i_cr 	= mttpar(4);
   n_g 	= mttpar(5);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);

## Unknown Inputs 

   mtty = zeros(1,1);

## BEGIN Code

## Code
  mtty(1) = mma_cr(i_cr,mttu1)*(e**((mttu1*n_g)/rt)*k_c*mttx1 - k_o*mttx2);
## END Code
endfunction
