
function [mttpar] = PgateC_numpar;
## [mttpar] = PgateC_numpar;
## System PgateC, representation numpar, language m; 
## File PgateC_numpar.m; 
## Generated by MTT on Wed Mar 11 09:06:12 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(5,1);

## BEGIN Code

## User defined code from PgateC_numpar.txt
  k_c	=  1.0; 
  k_o	=  1.0; 
  rt	=  1.0; 
  i_cr	=  1.0; 
  n_g	=  20;

  ## Set up the mttpar vector
  mttpar(1)	= k_c;
  mttpar(2)	= k_o;
  mttpar(3)	= rt;
  mttpar(4)	= i_cr;
  mttpar(5)	= n_g;
## END Code
endfunction
