
function [mtty] = PgateC_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = PgateC_odeo(mttx,mttu,mttt,mttpar);
## System PgateC, representation odeo, language m; 
## File PgateC_odeo.m; 
## Generated by MTT on Wed Mar 11 09:01:41 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_c 	= mttpar(1);
   k_o 	= mttpar(2);
   rt 	= mttpar(3);
   i_cr 	= mttpar(4);
   n_g 	= mttpar(5);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

## Inputs 
mttu1 = mttu(1);

## Unknown Inputs 

   mtty = zeros(1,1);

## BEGIN Code

## Code
  mtty(1) = mma_cr(i_cr,mttx1)*(e**((mttx1*n_g)/rt)*k_c*mttx2 - k_o*mttx3);
## END Code
endfunction
