
function [mttpar] = Segment_numpar;
## [mttpar] = Segment_numpar;
## System Segment, representation numpar, language m; 
## File Segment_numpar.m; 
## Generated by MTT on Mon Mar 30 09:29:42 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(24,1);

## BEGIN Code

## User defined code from Segment_numpar.txt
  c_m	=  1.0; 
  f	=  1.0; 
  k_c	=  1.0; 
  k_ch	=  1.0; 
  k_cm	=  1.0; 
  k_o	=  1.0; 
  k_oh	=  1.0; 
  k_om	=  1.0; 
  k_k	=  1.0; 
  k_l	=  1.0; 
  k_n	=  1.0; 
  rt	=  1.0; 
  v	=  1.0; 
  v_eq	=  1.0; 
  g_s	=  1.0; 
  kappa_k	=  1.0; 
  kappa_l	=  1.0; 
  kappa_n	=  1.0; 
  v_k	=  1.0; 
  v_l	=  1.0; 
  v_n	=  1.0; 
  v_unit	=  1.0; 
  x_g	=  1.0; 
  z	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= c_m;
  mttpar(2)	= f;
  mttpar(3)	= k_c;
  mttpar(4)	= k_ch;
  mttpar(5)	= k_cm;
  mttpar(6)	= k_o;
  mttpar(7)	= k_oh;
  mttpar(8)	= k_om;
  mttpar(9)	= k_k;
  mttpar(10)	= k_l;
  mttpar(11)	= k_n;
  mttpar(12)	= rt;
  mttpar(13)	= v;
  mttpar(14)	= v_eq;
  mttpar(15)	= g_s;
  mttpar(16)	= kappa_k;
  mttpar(17)	= kappa_l;
  mttpar(18)	= kappa_n;
  mttpar(19)	= v_k;
  mttpar(20)	= v_l;
  mttpar(21)	= v_n;
  mttpar(22)	= v_unit;
  mttpar(23)	= x_g;
  mttpar(24)	= z;
## END Code
endfunction
