% Default SUBS file
% File idRC_subs.r
% Generated by MTT on Tue Apr  3 09:43:38 BST 2001.


% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %% Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %% $Id: idNonlinearTanks_subs.r,v 1.2 2001/04/11 09:44:26 gawthrop Exp $
% %% $Log: idNonlinearTanks_subs.r,v $
% %% Revision 1.2  2001/04/11 09:44:26  gawthrop
% %% Fixed cc and c problems to do with pow(x,y) and integers
% %% mtt/lib/reduce/fix_c.r is included in rdae2dae and cse2smx_lang for
% %% -c, -cc and -oct options
% %%
% %% Revision 1.1  2001/04/05 12:00:18  gawthrop
% %% Identification example
% %%
% %% Revision 1.1  2000/12/28 09:13:38  peterg
% %% Initial revision
% %%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Put algebraic substitution commands here

%The following is now done automatically
% FOR ALL x,y LET x^y = pow(x,y);
END;
