% Steady-state parameter file (LiquidTurbine_sspar.r)
% Generated by MTT at Fri Nov 20 11:42:16 GMT 1998

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id: LiquidTurbine_sspar.r,v 1.2 2003/08/17 17:03:14 gawthrop Exp $
% % $Log: LiquidTurbine_sspar.r,v $
% % Revision 1.2  2003/08/17 17:03:14  gawthrop
% % Updated for new MTT
% %
% % Revision 1.1  2000/12/28 18:11:16  peterg
% % To RCS
% %
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Steady-state states
MTTX1 := 	1; % LiquidTurbine (j_s)
MTTX2 := 	p_0*c_t/rho; % LiquidTurbine_C1 (tank) - pressure = p0
MTTX3 := 	t_0*p_0*c_t*c_p; % LiquidTurbine_C1 (tank) - temp = t0
% Steady-state inputs
MTTU1 := 	q_0; % LiquidTurbine (Heat)
MTTU2 := 	0; % LiquidTurbine (Work)
;;END;
