% Default SUBS file
% File InvertedPendulumOnCart_subs.r
% Generated by MTT on Thu Nov  9 18:55:44 GMT 2000.


% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %% Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %% $Id: InvertedPendulumOnCart_subs.r,v 1.3 2001/04/11 09:44:26 gawthrop Exp $
% %% $Log: InvertedPendulumOnCart_subs.r,v $
% %% Revision 1.3  2001/04/11 09:44:26  gawthrop
% %% Fixed cc and c problems to do with pow(x,y) and integers
% %% mtt/lib/reduce/fix_c.r is included in rdae2dae and cse2smx_lang for
% %% -c, -cc and -oct options
% %%
% %% Revision 1.2  2001/04/02 10:57:57  gawthrop
% %% Added missing ;
% %%
% %% Revision 1.1  2000/12/28 18:00:45  peterg
% %% To RCS
% %%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Put algebraic substitution commands here

for all x let cos(x)^2+sin(x)^2 = 1;

FOR ALL x,y LET x^y = pow(x,y); % Use the pow function

ON ROUNDED; % No integer output

END;
