% Steady-state parameter file (HeatedRod_sspar.r)
% Generated by MTT at Thu Jun 25 09:32:38 BST 1998

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id: HeatedRod_sspar.r,v 1.1 2000/12/28 18:12:41 peterg Exp $
% % $Log: HeatedRod_sspar.r,v $
% % Revision 1.1  2000/12/28 18:12:41  peterg
% % To RCS
% %
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Steady-state states
MTTX1 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX2 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX3 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX4 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX5 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX6 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX7 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX8 := 	t_0*c_t; % HeatedRod_s_c_t (c)
MTTX9 := 	t_0*c_t; % HeatedRod_s_c_t (c)

% Steady-state inputs
MTTU1 := 	1.0; % HeatedRod (I_r)

;;END;
